server:
  port: 7602
eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
spring:
  application:
    name: reporting-service
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      database: h2
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        show_sql: true
        ddl-auto: create-drop
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        format_sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"




