server:
  port: 7601
eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
spring:
  mail:
    host: smtp.gmail.com
    username: nnadozieome@gmail.com
    password: nhxhocpyzfzmszuz
    port: 587
    from: "Bank App <no-reply@bank.com>"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: email-service
management:
  endpoints:
    web:
      exposure:
        include: "*"



